# Generated by Django 3.0.3 on 2020-04-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DramaRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('source', models.URLField()),
                ('episode', models.IntegerField()),
                ('max_episode', models.IntegerField()),
                ('timestamp', models.TimeField()),
            ],
        ),
    ]
