# Generated by Django 3.0.3 on 2020-04-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dramarecord',
            name='timestamp',
            field=models.CharField(max_length=8),
        ),
    ]
